theme: jekyll-theme-minimal
title: My Portfolio
logo: assets/logo.png
description: This is a quick overview of some of my personal projects. I showcase some of my skills in Machine/Depp Learning, Computer Visio, Data Science, Data Preparation, Data Visualization and general programming.
show_downloads: false
