theme: jekyll-theme-minimal
title: My Portfolio
logo: assets/logo.png
description: This is a small snapshot of my personal projects. I showcase some of my skills in Machine/Deep Learning, Computer Vision, Data Science, Data Preparation, Data Visualization and general programming.
show_downloads: false
